name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main  # adapte si ta branche principale est différente

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./   # adapte ce chemin si besoin (ex: dist/, build/)
          # remote-dir: www/  # décommente et modifie si ton dossier FTP n'est pas la racine
