name: 🚀 Deploy with FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: lukasbischof/ftp-deploy@v1.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./  # ou ./dist
          remoteDir: /www/
          protocol: ftps
