name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp-vip.alwaysdata.net
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./   # ou ./dist si vous avez un build
          server-dir: /www/FoodTruckCLSI/  # adapte selon ton projet
          log-level: verbose
